name: readthedocs
channels:
  - defaults
dependencies:
  - python=3.10
  - python-graphviz
  - pip
  - pip:
    - markdown-exec
    - mkdocs-exclude
    - mkdocs-jupyter
    - mkdocs-material
    - mkdocs-section-index
    - mkdocs
    - mkdocstrings
    - mkdocstrings-python
    - -e ../
    - pulser>=0.12.0
